import { CardSymbol, ScratchCardTier, Upgrade, PrestigeUpgrade } from "./types";

export const SYMBOLS: Record<string, CardSymbol> = {
  cherry: { type: "cherry", emoji: "🍒", multiplier: 1 },
  lemon: { type: "lemon", emoji: "🍋", multiplier: 1.5 },
  grape: { type: "grape", emoji: "🍇", multiplier: 2 },
  bell: { type: "bell", emoji: "🔔", multiplier: 3 },
  star: { type: "star", emoji: "⭐", multiplier: 5 },
  diamond: { type: "diamond", emoji: "💎", multiplier: 10 },
  seven: { type: "seven", emoji: "7️⃣", multiplier: 25 },
  crown: { type: "crown", emoji: "👑", multiplier: 50 },
};

export const CARD_TIERS: ScratchCardTier[] = [
  {
    id: "penny",
    name: "Penny Scratch",
    cost: 10,
    unlockCost: 0,
    unlocked: true,
    gridCols: 3,
    gridRows: 3,
    matchRequired: 3,
    symbols: [SYMBOLS.cherry, SYMBOLS.lemon, SYMBOLS.grape, SYMBOLS.bell],
    jackpotMultiplier: 10,
    color: "from-green-600 to-green-800",
    gradientFrom: "#16a34a",
    gradientTo: "#166534",
    description: "A humble start. Match 3 to win!",
  },
  {
    id: "silver",
    name: "Silver Scratch",
    cost: 50,
    unlockCost: 500,
    unlocked: false,
    gridCols: 3,
    gridRows: 3,
    matchRequired: 3,
    symbols: [SYMBOLS.cherry, SYMBOLS.lemon, SYMBOLS.grape, SYMBOLS.bell, SYMBOLS.star],
    jackpotMultiplier: 25,
    color: "from-slate-400 to-slate-600",
    gradientFrom: "#94a3b8",
    gradientTo: "#475569",
    description: "Better odds, bigger prizes.",
  },
  {
    id: "gold",
    name: "Gold Scratch",
    cost: 200,
    unlockCost: 5000,
    unlocked: false,
    gridCols: 4,
    gridRows: 3,
    matchRequired: 3,
    symbols: [SYMBOLS.lemon, SYMBOLS.grape, SYMBOLS.bell, SYMBOLS.star, SYMBOLS.diamond],
    jackpotMultiplier: 50,
    color: "from-yellow-500 to-yellow-700",
    gradientFrom: "#eab308",
    gradientTo: "#a16207",
    description: "4x3 grid with premium symbols.",
  },
  {
    id: "diamond",
    name: "Diamond Scratch",
    cost: 1000,
    unlockCost: 50000,
    unlocked: false,
    gridCols: 4,
    gridRows: 4,
    matchRequired: 3,
    symbols: [SYMBOLS.grape, SYMBOLS.bell, SYMBOLS.star, SYMBOLS.diamond, SYMBOLS.seven],
    jackpotMultiplier: 100,
    color: "from-cyan-400 to-blue-600",
    gradientFrom: "#22d3ee",
    gradientTo: "#2563eb",
    description: "4x4 grid with rare symbols.",
  },
  {
    id: "royal",
    name: "Royal Flush",
    cost: 5000,
    unlockCost: 500000,
    unlocked: false,
    gridCols: 5,
    gridRows: 5,
    matchRequired: 3,
    symbols: [SYMBOLS.bell, SYMBOLS.star, SYMBOLS.diamond, SYMBOLS.seven, SYMBOLS.crown],
    jackpotMultiplier: 250,
    color: "from-purple-500 to-pink-600",
    gradientFrom: "#a855f7",
    gradientTo: "#db2777",
    description: "The ultimate scratch card. Huge jackpots!",
  },
];

export const UPGRADES: Upgrade[] = [
  {
    id: "luck_boost",
    name: "Lucky Charm",
    description: "Increases chance of rare symbols appearing.",
    baseCost: 100,
    currentLevel: 0,
    maxLevel: 10,
    costMultiplier: 2.5,
    effect: "+10% rare symbol chance per level",
    icon: "🍀",
  },
  {
    id: "payout_boost",
    name: "Payout Multiplier",
    description: "Multiply all winnings by a bonus factor.",
    baseCost: 250,
    currentLevel: 0,
    maxLevel: 10,
    costMultiplier: 3,
    effect: "+15% payout per level",
    icon: "💰",
  },
  {
    id: "auto_scratch",
    name: "Scratch Bot",
    description: "Automatically scratches cards for you.",
    baseCost: 500,
    currentLevel: 0,
    maxLevel: 5,
    costMultiplier: 4,
    effect: "Auto-scratches faster per level",
    icon: "🤖",
  },
  {
    id: "scratch_speed",
    name: "Scratch Speed",
    description: "Larger scratch radius, reveal faster.",
    baseCost: 150,
    currentLevel: 0,
    maxLevel: 5,
    costMultiplier: 2,
    effect: "+20% scratch radius per level",
    icon: "⚡",
  },
  {
    id: "bulk_discount",
    name: "Bulk Buyer",
    description: "Reduced cost on all scratch cards.",
    baseCost: 300,
    currentLevel: 0,
    maxLevel: 5,
    costMultiplier: 3,
    effect: "-10% card cost per level",
    icon: "🏷️",
  },
  {
    id: "jackpot_chance",
    name: "Jackpot Magnet",
    description: "Increases jackpot trigger chance.",
    baseCost: 1000,
    currentLevel: 0,
    maxLevel: 5,
    costMultiplier: 5,
    effect: "+5% jackpot chance per level",
    icon: "🎰",
  },
];

export const PRESTIGE_UPGRADES: PrestigeUpgrade[] = [
  {
    id: "start_bonus",
    name: "Starting Bonus",
    description: "Start each run with $500.",
    cost: 3,
    purchased: false,
    icon: "🎁",
  },
  {
    id: "permanent_luck",
    name: "Permanent Luck",
    description: "+20% rare symbol chance permanently.",
    cost: 5,
    purchased: false,
    icon: "🌟",
  },
  {
    id: "auto_start",
    name: "Auto-Start",
    description: "Scratch Bot starts at level 1.",
    cost: 4,
    purchased: false,
    icon: "🚀",
  },
  {
    id: "earn_multiplier",
    name: "Golden Touch",
    description: "+25% to all earnings permanently.",
    cost: 8,
    purchased: false,
    icon: "✨",
  },
  {
    id: "discount",
    name: "Loyalty Card",
    description: "-15% to all card costs permanently.",
    cost: 6,
    purchased: false,
    icon: "💳",
  },
  {
    id: "double_jackpot",
    name: "Double Jackpot",
    description: "All jackpot values are doubled.",
    cost: 10,
    purchased: false,
    icon: "💎",
  },
];

export function getUpgradeCost(upgrade: Upgrade): number {
  return Math.floor(upgrade.baseCost * Math.pow(upgrade.costMultiplier, upgrade.currentLevel));
}

export function formatMoney(amount: number): string {
  if (amount >= 1e12) return `$${(amount / 1e12).toFixed(1)}T`;
  if (amount >= 1e9) return `$${(amount / 1e9).toFixed(1)}B`;
  if (amount >= 1e6) return `$${(amount / 1e6).toFixed(1)}M`;
  if (amount >= 1e3) return `$${(amount / 1e3).toFixed(1)}K`;
  return `$${Math.floor(amount)}`;
}
