import {
  SymbolDef,
  CardType,
  Catalogue,
  Upgrade,
  PrestigeUpgrade,
} from "./types";

export const SYMBOLS: Record<string, SymbolDef> = {
  // Win symbols
  cherry: { id: "cherry", emoji: "🍒", name: "Cherry", isTrap: false, value: 1 },
  grape: { id: "grape", emoji: "🍇", name: "Grape", isTrap: false, value: 2 },
  bell: { id: "bell", emoji: "🔔", name: "Bell", isTrap: false, value: 3 },
  star: { id: "star", emoji: "⭐", name: "Star", isTrap: false, value: 5 },
  seven: { id: "seven", emoji: "7️⃣", name: "Lucky Seven", isTrap: false, value: 10 },
  crown: { id: "crown", emoji: "👑", name: "Crown", isTrap: false, value: 25 },
  diamond: { id: "diamond", emoji: "💎", name: "Diamond", isTrap: false, value: 50 },
  apple: { id: "apple", emoji: "🍎", name: "Apple", isTrap: false, value: 2 },
  leaf: { id: "leaf", emoji: "🍃", name: "Leaf", isTrap: false, value: 1 },
  bee: { id: "bee", emoji: "🐝", name: "Bee", isTrap: false, value: 3 },
  flower: { id: "flower", emoji: "🌸", name: "Flower", isTrap: false, value: 2 },
  cat_lucky: { id: "cat_lucky", emoji: "🐱", name: "Lucky Cat", isTrap: false, value: 10 },
  paw: { id: "paw", emoji: "🐾", name: "Paw", isTrap: false, value: 5 },
  jellyfish: { id: "jellyfish", emoji: "🪼", name: "Jellyfish", isTrap: false, value: 20 },
  shell: { id: "shell", emoji: "🐚", name: "Shell", isTrap: false, value: 3 },
  fish: { id: "fish", emoji: "🐟", name: "Fish", isTrap: false, value: 5 },
  dollar: { id: "dollar", emoji: "💵", name: "Cash", isTrap: false, value: 1 },
  coin: { id: "coin", emoji: "🪙", name: "Coin", isTrap: false, value: 2 },
  dice1: { id: "dice1", emoji: "🎲", name: "Safe Dice", isTrap: false, value: 5 },
  dice2: { id: "dice2", emoji: "🎯", name: "Target", isTrap: false, value: 8 },
  bag_sand: { id: "bag_sand", emoji: "🏖️", name: "Sand Dollar", isTrap: false, value: 10 },
  tree: { id: "tree", emoji: "🌴", name: "Palm Tree", isTrap: false, value: 5 },
  pumpkin: { id: "pumpkin", emoji: "🎃", name: "Pumpkin", isTrap: false, value: 15 },
  bat: { id: "bat", emoji: "🦇", name: "Bat", isTrap: false, value: 5 },
  candy: { id: "candy", emoji: "🍬", name: "Candy", isTrap: false, value: 3 },
  ghost: { id: "ghost", emoji: "👻", name: "Ghost", isTrap: false, value: 10 },
  slot7: { id: "slot7", emoji: "🎰", name: "Slot", isTrap: false, value: 20 },
  rocket: { id: "rocket", emoji: "🚀", name: "Rocket", isTrap: false, value: 30 },
  moon: { id: "moon", emoji: "🌙", name: "Moon", isTrap: false, value: 15 },
  card_pack: { id: "card_pack", emoji: "🃏", name: "Card", isTrap: false, value: 25 },
  gift: { id: "gift", emoji: "🎁", name: "Gift", isTrap: false, value: 10 },
  xmas_tree: { id: "xmas_tree", emoji: "🎄", name: "Xmas Tree", isTrap: false, value: 20 },
  snowman: { id: "snowman", emoji: "⛄", name: "Snowman", isTrap: false, value: 8 },
  bank: { id: "bank", emoji: "🏦", name: "Bank", isTrap: false, value: 50 },
  berry: { id: "berry", emoji: "🫐", name: "Berry", isTrap: false, value: 5 },
  basket: { id: "basket", emoji: "🧺", name: "Basket", isTrap: false, value: 3 },

  // Trap symbols
  worm: { id: "worm", emoji: "🐛", name: "Worm", isTrap: true, value: -5 },
  black_cat: { id: "black_cat", emoji: "🐈‍⬛", name: "Black Cat", isTrap: true, value: -10 },
  snake_eyes: { id: "snake_eyes", emoji: "🐍", name: "Snake Eyes", isTrap: true, value: -8 },
  plastic_bag: { id: "plastic_bag", emoji: "🛍️", name: "Plastic Bag", isTrap: true, value: -15 },
  bomb: { id: "bomb", emoji: "💣", name: "Bomb", isTrap: true, value: -20 },
};

export const CATALOGUES: Catalogue[] = [
  {
    id: "cat_1",
    name: "Starter Pack",
    icon: "📦",
    description: "Basic scratch cards for beginners",
    unlockCost: 0,
    unlocked: true,
    unlockRequirement: "Available from start",
  },
  {
    id: "cat_2",
    name: "Beach Bundle",
    icon: "🏖️",
    description: "Seaside themed cards with bigger prizes",
    unlockCost: 0,
    unlocked: false,
    unlockRequirement: "Prestige once to unlock",
  },
  {
    id: "cat_3",
    name: "Spooky Selection",
    icon: "🎃",
    description: "Halloween cards with high risk/reward",
    unlockCost: 0,
    unlocked: false,
    unlockRequirement: "Prestige twice to unlock",
  },
  {
    id: "cat_4",
    name: "Deluxe Collection",
    icon: "👑",
    description: "The ultimate scratch cards",
    unlockCost: 0,
    unlocked: false,
    unlockRequirement: "Prestige 3 times to unlock",
  },
];

export const CARD_TYPES: CardType[] = [
  // Catalogue 1: Starter Pack
  {
    id: "two_win",
    name: "Two Win",
    icon: "💵",
    catalogueId: "cat_1",
    baseCost: 10,
    riskLevel: "safe",
    zones: 3,
    symbolsPerZone: 1,
    matchRequired: 2,
    winSymbols: ["dollar", "coin", "cherry", "bell"],
    trapSymbols: [],
    jackpotMultiplier: 5,
    basePrize: 20,
    description: "Match 2 of 3 symbols to win. No traps!",
    colorFrom: "#22c55e",
    colorTo: "#15803d",
    unlocked: true,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "mini_scratch",
    name: "Mini Scratch",
    icon: "🪙",
    catalogueId: "cat_1",
    baseCost: 100,
    riskLevel: "low",
    zones: 4,
    symbolsPerZone: 1,
    matchRequired: 2,
    winSymbols: ["coin", "cherry", "grape", "bell", "star"],
    trapSymbols: [],
    jackpotMultiplier: 10,
    basePrize: 150,
    description: "4 zones, match 2 for prizes.",
    colorFrom: "#3b82f6",
    colorTo: "#1d4ed8",
    unlocked: false,
    unlockCost: 500,
    isPrestige: false,
  },
  {
    id: "apple_tree",
    name: "Apple Tree",
    icon: "🍎",
    catalogueId: "cat_1",
    baseCost: 1000,
    riskLevel: "medium",
    zones: 6,
    symbolsPerZone: 1,
    matchRequired: 2,
    winSymbols: ["apple", "leaf", "bee", "flower"],
    trapSymbols: ["worm"],
    jackpotMultiplier: 15,
    basePrize: 2000,
    description: "Earn per apple! Watch out for worms! 🐛",
    colorFrom: "#ef4444",
    colorTo: "#b91c1c",
    unlocked: false,
    unlockCost: 5000,
    isPrestige: false,
  },
  {
    id: "quick_cash",
    name: "Quick Cash",
    icon: "💰",
    catalogueId: "cat_1",
    baseCost: 10000,
    riskLevel: "medium",
    zones: 6,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["star", "bell", "seven", "crown"],
    trapSymbols: [],
    jackpotMultiplier: 25,
    basePrize: 25000,
    description: "Match 3, high payouts. No traps!",
    colorFrom: "#eab308",
    colorTo: "#a16207",
    unlocked: false,
    unlockCost: 50000,
    isPrestige: false,
  },
  {
    id: "lucky_cat",
    name: "Lucky Cat",
    icon: "🐱",
    catalogueId: "cat_1",
    baseCost: 300000,
    riskLevel: "high",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["cat_lucky", "paw", "star", "crown"],
    trapSymbols: ["black_cat"],
    jackpotMultiplier: 50,
    basePrize: 750000,
    description: "Big jackpots but beware the black cat! 🐈‍⬛",
    colorFrom: "#f59e0b",
    colorTo: "#d97706",
    unlocked: false,
    unlockCost: 1500000,
    isPrestige: false,
  },
  {
    id: "final_chance_1",
    name: "Final Chance",
    icon: "💀",
    catalogueId: "cat_1",
    baseCost: 50000000,
    riskLevel: "ultra",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["crown", "diamond", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 100,
    basePrize: 50000000,
    description: "Prestige trigger! Scratch to reset your run.",
    colorFrom: "#7c3aed",
    colorTo: "#4c1d95",
    unlocked: false,
    unlockCost: 0,
    isPrestige: true,
  },

  // Catalogue 2: Beach Bundle
  {
    id: "sand_dollars",
    name: "Sand Dollars",
    icon: "🏖️",
    catalogueId: "cat_2",
    baseCost: 20000000,
    riskLevel: "medium",
    zones: 6,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["bag_sand", "shell", "tree", "fish"],
    trapSymbols: [],
    jackpotMultiplier: 30,
    basePrize: 50000000,
    description: "Beach vibes with steady payouts.",
    colorFrom: "#06b6d4",
    colorTo: "#0891b2",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "scratch_my_back",
    name: "Scratch My Back",
    icon: "🐢",
    catalogueId: "cat_2",
    baseCost: 500000000,
    riskLevel: "high",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["jellyfish", "shell", "fish", "star"],
    trapSymbols: ["plastic_bag"],
    jackpotMultiplier: 60,
    basePrize: 1500000000,
    description: "Turtle shell card. Jellyfish = big wins! 🪼",
    colorFrom: "#10b981",
    colorTo: "#047857",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "snake_eyes",
    name: "Snake Eyes",
    icon: "🎲",
    catalogueId: "cat_2",
    baseCost: 10000000000,
    riskLevel: "very_high",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["dice1", "dice2", "star", "seven"],
    trapSymbols: ["snake_eyes"],
    jackpotMultiplier: 80,
    basePrize: 40000000000,
    description: "Roll the dice! Avoid snake eyes! 🐍",
    colorFrom: "#dc2626",
    colorTo: "#991b1b",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "the_bomb",
    name: "The Bomb",
    icon: "💣",
    catalogueId: "cat_2",
    baseCost: 200000000000,
    riskLevel: "very_high",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["star", "diamond", "crown", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 100,
    basePrize: 1000000000000,
    description: "Massive prizes but one bomb ends it all!",
    colorFrom: "#f97316",
    colorTo: "#c2410c",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "final_chance_2",
    name: "Final Chance",
    icon: "💀",
    catalogueId: "cat_2",
    baseCost: 5000000000000,
    riskLevel: "ultra",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["crown", "diamond", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 150,
    basePrize: 5000000000000,
    description: "Prestige trigger for Catalogue 2.",
    colorFrom: "#7c3aed",
    colorTo: "#4c1d95",
    unlocked: false,
    unlockCost: 0,
    isPrestige: true,
  },

  // Catalogue 3: Spooky Selection
  {
    id: "bank_break",
    name: "Bank Break",
    icon: "🏦",
    catalogueId: "cat_3",
    baseCost: 200000000000000,
    riskLevel: "medium",
    zones: 6,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["bank", "coin", "dollar", "star"],
    trapSymbols: [],
    jackpotMultiplier: 40,
    basePrize: 800000000000000,
    description: "Break the bank! Steady returns.",
    colorFrom: "#8b5cf6",
    colorTo: "#6d28d9",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "xmas_countdown",
    name: "Xmas Countdown",
    icon: "🎄",
    catalogueId: "cat_3",
    baseCost: 10000000000000000,
    riskLevel: "medium",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["xmas_tree", "gift", "snowman", "candy", "star"],
    trapSymbols: [],
    jackpotMultiplier: 50,
    basePrize: 50000000000000000,
    description: "Holiday themed! No traps, pure prizes.",
    colorFrom: "#16a34a",
    colorTo: "#15803d",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "thrift_store",
    name: "Thrift Store",
    icon: "🏪",
    catalogueId: "cat_3",
    baseCost: 500000000000000000,
    riskLevel: "high",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["gift", "star", "crown", "diamond"],
    trapSymbols: ["worm"],
    jackpotMultiplier: 70,
    basePrize: 2500000000000000000,
    description: "Hidden treasures and hidden worms!",
    colorFrom: "#a855f7",
    colorTo: "#7c3aed",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "berry_picking",
    name: "Berry Picking",
    icon: "🫐",
    catalogueId: "cat_3",
    baseCost: 20000000000000000000,
    riskLevel: "high",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["berry", "apple", "flower", "star", "crown"],
    trapSymbols: ["worm"],
    jackpotMultiplier: 90,
    basePrize: 150000000000000000000,
    description: "Pick berries, dodge worms!",
    colorFrom: "#6366f1",
    colorTo: "#4338ca",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "final_chance_3",
    name: "Final Chance",
    icon: "💀",
    catalogueId: "cat_3",
    baseCost: 200000000000000000000,
    riskLevel: "ultra",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["crown", "diamond", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 200,
    basePrize: 200000000000000000000,
    description: "Prestige trigger for Catalogue 3.",
    colorFrom: "#7c3aed",
    colorTo: "#4c1d95",
    unlocked: false,
    unlockCost: 0,
    isPrestige: true,
  },

  // Catalogue 4: Deluxe Collection
  {
    id: "trick_or_treat",
    name: "Trick Or Treat",
    icon: "🎃",
    catalogueId: "cat_4",
    baseCost: 60000000000000000000000,
    riskLevel: "medium",
    zones: 8,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["pumpkin", "candy", "bat", "ghost", "star"],
    trapSymbols: ["black_cat"],
    jackpotMultiplier: 80,
    basePrize: 400000000000000000000000,
    description: "Halloween treats with spooky traps!",
    colorFrom: "#f97316",
    colorTo: "#ea580c",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "slot_machine",
    name: "Slot Machine",
    icon: "🎰",
    catalogueId: "cat_4",
    baseCost: 5000000000000000000000000,
    riskLevel: "high",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["slot7", "star", "diamond", "crown", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 120,
    basePrize: 40000000000000000000000000,
    description: "Spin to win! Bombs end your streak!",
    colorFrom: "#e11d48",
    colorTo: "#be123c",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "to_the_moon",
    name: "To The Moon",
    icon: "🚀",
    catalogueId: "cat_4",
    baseCost: 800000000000000000000000000,
    riskLevel: "high",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["rocket", "moon", "star", "diamond", "crown"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 150,
    basePrize: 8000000000000000000000000000,
    description: "To the moon! Massive jackpots await!",
    colorFrom: "#0ea5e9",
    colorTo: "#0284c7",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "booster_pack",
    name: "Booster Pack",
    icon: "🃏",
    catalogueId: "cat_4",
    baseCost: 30000000000000000000000000000000,
    riskLevel: "high",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["card_pack", "star", "diamond", "crown", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 200,
    basePrize: 300000000000000000000000000000000,
    description: "Ultimate card pack! Best with Picky Eater.",
    colorFrom: "#d946ef",
    colorTo: "#a21caf",
    unlocked: false,
    unlockCost: 0,
    isPrestige: false,
  },
  {
    id: "final_chance_4",
    name: "Final Chance",
    icon: "💀",
    catalogueId: "cat_4",
    baseCost: 1000000000000000000000000000000000,
    riskLevel: "ultra",
    zones: 9,
    symbolsPerZone: 1,
    matchRequired: 3,
    winSymbols: ["crown", "diamond", "seven"],
    trapSymbols: ["bomb"],
    jackpotMultiplier: 500,
    basePrize: 1000000000000000000000000000000000,
    description: "The ultimate prestige trigger.",
    colorFrom: "#7c3aed",
    colorTo: "#4c1d95",
    unlocked: false,
    unlockCost: 0,
    isPrestige: true,
  },
];

export const UPGRADES: Upgrade[] = [
  // Luck
  { id: "luck_1", name: "Lucky Charm", description: "+5% base luck. Reduces trap frequency.", category: "luck", cost: 50, purchased: false, icon: "🍀", phase: "early" },
  { id: "luck_2", name: "Fortune Fingers", description: "+10% luck, reduces black cat frequency.", category: "luck", cost: 500, purchased: false, icon: "🤞", phase: "early", prerequisite: "luck_1" },
  { id: "luck_3", name: "Jackpot Aura", description: "+20% jackpot probability.", category: "luck", cost: 50000, purchased: false, icon: "✨", phase: "mid", prerequisite: "luck_2" },
  { id: "luck_4", name: "Blessed Hands", description: "+35% overall luck multiplier.", category: "luck", cost: 5000000, purchased: false, icon: "🙌", phase: "late", prerequisite: "luck_3" },

  // Scratch Power
  { id: "power_1", name: "Sharp Nails", description: "Wider scratch stroke per drag.", category: "power", cost: 100, purchased: false, icon: "💅", phase: "early" },
  { id: "power_2", name: "Steel Grip", description: "2x scratch width.", category: "power", cost: 1000, purchased: false, icon: "🦾", phase: "early", prerequisite: "power_1" },
  { id: "power_3", name: "Power Swipe", description: "4x scratch area per stroke.", category: "power", cost: 100000, purchased: false, icon: "⚡", phase: "mid", prerequisite: "power_2" },
  { id: "power_4", name: "One-Stroke Master", description: "Near-instant card clear.", category: "power", cost: 10000000, purchased: false, icon: "🌪️", phase: "late", prerequisite: "power_3" },

  // Scratch Area
  { id: "area_1", name: "Wide Zone", description: "+30% scratch zone size.", category: "area", cost: 200, purchased: false, icon: "📐", phase: "early" },
  { id: "area_2", name: "Full Coverage", description: "+80% scratch zone size.", category: "area", cost: 50000, purchased: false, icon: "📏", phase: "mid", prerequisite: "area_1" },

  // Reward Multipliers
  { id: "multi_1", name: "2x Winnings", description: "Double all card prizes.", category: "multi", cost: 100000, purchased: false, icon: "✖️", phase: "mid" },
  { id: "multi_2", name: "Big Spender", description: "+50% on cards over $1,000.", category: "multi", cost: 1000000, purchased: false, icon: "💎", phase: "late", prerequisite: "multi_1" },
  { id: "multi_3", name: "Jackpot Multiplier", description: "3x jackpot prize values.", category: "multi", cost: 50000000, purchased: false, icon: "🎰", phase: "late", prerequisite: "multi_2" },

  // Automation
  { id: "auto_unlock", name: "Unlock Auto Scratcher", description: "Enables automatic card processing.", category: "auto", cost: 5000, purchased: false, icon: "🤖", phase: "mid" },
  { id: "auto_queue_1", name: "Extended Queue", description: "+5 card queue capacity.", category: "auto", cost: 25000, purchased: false, icon: "📋", phase: "mid", prerequisite: "auto_unlock" },
  { id: "auto_queue_2", name: "Mega Queue", description: "+20 card queue capacity.", category: "auto", cost: 5000000, purchased: false, icon: "📦", phase: "late", prerequisite: "auto_queue_1" },
  { id: "auto_speed", name: "Turbo Speed", description: "2x auto-scratch processing rate.", category: "auto", cost: 100000, purchased: false, icon: "⏩", phase: "mid", prerequisite: "auto_queue_1" },

  // Quality of Life
  { id: "spacebar", name: "Spacebar Confirm", description: "Press SPACE to quickly confirm cards.", category: "qol", cost: 10000, purchased: false, icon: "⌨️", phase: "mid" },
  { id: "fan", name: "Fan Gadget", description: "Auto-discards cards with traps.", category: "qol", cost: 50000, purchased: false, icon: "🌀", phase: "mid" },
  { id: "recycle", name: "Recycle Bonus", description: "Trashed cards give 10% value back.", category: "qol", cost: 200000, purchased: false, icon: "♻️", phase: "late" },
];

export const PRESTIGE_UPGRADES: PrestigeUpgrade[] = [
  { id: "lucky_legacy", name: "Lucky Legacy", description: "+15% base luck permanently.", cost: 15, purchased: false, icon: "🍀" },
  { id: "head_start", name: "Head Start Capital", description: "Start each run with $500.", cost: 10, purchased: false, icon: "💰" },
  { id: "speed_demon", name: "Speed Demon", description: "Start with Scratch Power tier 2.", cost: 20, purchased: false, icon: "⚡" },
  { id: "scratch_memory", name: "Scratch Memory", description: "Auto Scratcher unlocked from start.", cost: 20, purchased: false, icon: "🤖" },
  { id: "golden_hands", name: "Golden Hands", description: "+25% to all prize values permanently.", cost: 25, purchased: false, icon: "✨" },
  { id: "jackpot_magnet", name: "Jackpot Magnet", description: "Jackpot frequency doubled.", cost: 30, purchased: false, icon: "🧲" },
  { id: "banco", name: "Banco", description: "Bankruptcy disabled for 1st run after prestige.", cost: 35, purchased: false, icon: "🏦" },
  { id: "recycler_pro", name: "Recycler Pro", description: "Trashed cards give 10% value back.", cost: 15, purchased: false, icon: "♻️" },
];

export const CARD_LEVELS: { level: number; prizeMultiplier: number }[] = [
  { level: 1, prizeMultiplier: 1 },
  { level: 2, prizeMultiplier: 1.5 },
  { level: 3, prizeMultiplier: 2 },
  { level: 4, prizeMultiplier: 3 },
  { level: 5, prizeMultiplier: 5 },
  { level: 6, prizeMultiplier: 8 },
  { level: 7, prizeMultiplier: 12 },
  { level: 8, prizeMultiplier: 20 },
  { level: 9, prizeMultiplier: 35 },
  { level: 10, prizeMultiplier: 50 },
];

export function getCardLevelMultiplier(level: number): number {
  const entry = CARD_LEVELS.find((l) => l.level === level);
  return entry?.prizeMultiplier ?? 1;
}

export function formatMoney(amount: number): string {
  if (amount >= 1e33) return `$${(amount / 1e33).toFixed(1)}No`;
  if (amount >= 1e30) return `$${(amount / 1e30).toFixed(1)}Oc`;
  if (amount >= 1e27) return `$${(amount / 1e27).toFixed(1)}Sp`;
  if (amount >= 1e24) return `$${(amount / 1e24).toFixed(1)}Sx`;
  if (amount >= 1e21) return `$${(amount / 1e21).toFixed(1)}Qi`;
  if (amount >= 1e18) return `$${(amount / 1e18).toFixed(1)}Qa`;
  if (amount >= 1e15) return `$${(amount / 1e15).toFixed(1)}T`;
  if (amount >= 1e12) return `$${(amount / 1e12).toFixed(1)}B`;
  if (amount >= 1e9) return `$${(amount / 1e9).toFixed(1)}M`;
  if (amount >= 1e6) return `$${(amount / 1e6).toFixed(1)}M`;
  if (amount >= 1e3) return `$${(amount / 1e3).toFixed(1)}K`;
  return `$${Math.floor(amount)}`;
}
